FROM node:latest

MAINTAINER Vishwas B Anand

ENV NODE_ENV=production
ENV PORT=3000

COPY . /var/www
WORKDIR /var/www

VOLUME ["/var/www","/logs"]

RUN  npm install

EXPOSE $PORT

ENTRYPOINT ["node","app"]

